### ISSUE TITLE
Eye candy

### ISSUE THREAD

**Issue by johndpope** [crescentflare/DynamicAppConfig#1]
![Screen Shot 2019-06-14 at 2 53 44 pm](https://user-images.githubusercontent.com/289994/59484242-41296480-8eb4-11e9-96fb-6ba93fd4d540.png)

**Comment by johndpope** [comment]
<img width="294" alt="Screen Shot 2019-06-14 at 3 51 10 pm" src="https://user-images.githubusercontent.com/289994/59486358-691cc600-8ebc-11e9-93cb-b7eb0eefeb00.png">
![Uploading Screen Shot 2019-06-14 at 3.51.03 pm.png…]()

**Comment by crescentflare** [comment]
The screenshot has been added (also added an Android screenshot). I'm not sure the code in the image though, people may try to copy the text from the image.
